package deploy

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/kodedlabs/ship/internal/ai"
	"github.com/kodedlabs/ship/internal/config"
	"github.com/kodedlabs/ship/internal/generator"
	sshclient "github.com/kodedlabs/ship/internal/ssh"
)

type Executor struct {
	client   *sshclient.Client
	cfg      *config.Config
	plan     *ai.DeploymentPlan
	appDir   string
	localDir string
	appPort  int
}

type StepResult struct {
	Name    string
	Success bool
	Output  string
	Err     error
}

func New(client *sshclient.Client, cfg *config.Config, plan *ai.DeploymentPlan, localDir string, appPort int) *Executor {
	appDir := fmt.Sprintf("$HOME/ship/%s", cfg.App.Name)
	return &Executor{client: client, cfg: cfg, plan: plan, appDir: appDir, localDir: localDir, appPort: appPort}
}

func (e *Executor) Run(stepFn func(name string)) []StepResult {
	var results []StepResult
	steps := []struct {
		name string
		fn   func() error
	}{
		{"Create app directory", e.createAppDir},
		{"Upload source code", e.uploadSourceCode},
		{"Upload Dockerfile", e.uploadDockerfile},
		{"Upload Docker Compose", e.uploadDockerCompose},
		{"Upload Nginx config", e.uploadNginxConfig},
		{"Upload .env template", e.uploadEnvTemplate},
		{"Build & start containers", e.startContainers},
		{"Health check", e.healthCheck},
	}

	for _, step := range steps {
		if stepFn != nil {
			stepFn(step.name)
		}
		err := step.fn()
		results = append(results, StepResult{
			Name:    step.name,
			Success: err == nil,
			Err:     err,
		})
		if err != nil {
			break
		}
	}
	return results
}

func (e *Executor) createAppDir() error {
	// Resolve $HOME on the remote first, then create the dir
	out, _, err := e.client.Exec("echo $HOME")
	if err != nil {
		return fmt.Errorf("resolving home dir: %w", err)
	}
	home := strings.TrimSpace(out)
	e.appDir = strings.Replace(e.appDir, "$HOME", home, 1)
	return e.client.MkdirAll(e.appDir)
}

func (e *Executor) uploadSourceCode() error {
	return e.client.UploadDir(e.localDir, e.appDir)
}

func (e *Executor) uploadDockerfile() error {
	if e.plan.Dockerfile == "" {
		return nil
	}
	return e.client.WriteFile(fmt.Sprintf("%s/Dockerfile", e.appDir), e.plan.Dockerfile)
}

func (e *Executor) uploadDockerCompose() error {
	if e.plan.DockerCompose == "" {
		return nil
	}
	return e.client.WriteFile(fmt.Sprintf("%s/docker-compose.yml", e.appDir), e.plan.DockerCompose)
}

func (e *Executor) uploadNginxConfig() error {
	nginxCfg := e.plan.NginxConfig

	// When there's no domain, the AI often generates an HTTP→HTTPS redirect that
	// breaks plain-IP access. Override with a known-good HTTP-only config instead.
	if e.plan.Domain == "" || !e.plan.SSLEnabled {
		nginxCfg = generator.NginxConfig("", e.cfg.App.Name, e.appPort, false)
	}

	if nginxCfg == "" {
		return nil
	}
	return e.client.WriteFile(fmt.Sprintf("%s/nginx.conf", e.appDir), nginxCfg)
}

func (e *Executor) uploadEnvTemplate() error {
	// Only write .env if one doesn't already exist on the server
	remotePath := fmt.Sprintf("%s/.env", e.appDir)
	out, _, _ := e.client.Exec(fmt.Sprintf("test -f %s && echo exists", remotePath))
	if strings.TrimSpace(out) == "exists" {
		return nil
	}
	var sb strings.Builder
	sb.WriteString("# Generated by Ship — fill in the values below\n")
	for k, v := range e.plan.EnvVars {
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, v))
	}
	return e.client.WriteFile(remotePath, sb.String())
}

func (e *Executor) startContainers() error {
	logFile := fmt.Sprintf("%s/deploy.log", e.appDir)

	// stop and remove ALL containers (dedicated VPS — Ship owns Docker state),
	// prune corrupted build cache, then bring up fresh
	launchCmd := fmt.Sprintf(
		"cd %s && nohup bash -c 'docker ps -q | xargs -r docker stop 2>/dev/null; docker ps -aq | xargs -r docker rm 2>/dev/null; docker builder prune -f 2>/dev/null; docker compose up -d --build' > %s 2>&1 &",
		e.appDir, logFile,
	)
	if _, stderr, err := e.client.Exec(launchCmd); err != nil {
		return fmt.Errorf("launching containers: %w\n%s", err, stderr)
	}

	// Poll until at least one container is running (up to 3 minutes)
	deadline := time.Now().Add(3 * time.Minute)
	for time.Now().Before(deadline) {
		time.Sleep(5 * time.Second)
		out, _, _ := e.client.Exec(fmt.Sprintf("cd %s && docker compose ps --status running --quiet 2>/dev/null | wc -l", e.appDir))
		if strings.TrimSpace(out) != "0" && strings.TrimSpace(out) != "" {
			return nil
		}
	}

	// Timed out — grab the last few lines of the log for a useful error
	tail, _, _ := e.client.Exec(fmt.Sprintf("tail -20 %s 2>/dev/null", logFile))
	return fmt.Errorf("containers did not start within 3 minutes\n\nBuild log:\n%s", tail)
}

func (e *Executor) healthCheck() error {
	host := e.cfg.Server.Host
	hasDomain := e.plan.Domain != ""
	if hasDomain {
		host = e.plan.Domain
	}

	// Only use HTTPS when there's a real domain — IP addresses can't have certs
	scheme := "http"
	if e.plan.SSLEnabled && hasDomain {
		scheme = "https"
	}
	url := fmt.Sprintf("%s://%s", scheme, host)

	// Don't follow redirects — a 3xx from nginx counts as "app is up"
	client := &http.Client{
		Timeout: 10 * time.Second,
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	var lastErr error
	for i := 0; i < 6; i++ {
		resp, err := client.Get(url)
		if err == nil {
			resp.Body.Close()
			if resp.StatusCode < 500 {
				return nil
			}
		}
		lastErr = err
		time.Sleep(5 * time.Second)
	}
	return fmt.Errorf("health check failed for %s: %w", url, lastErr)
}

func (e *Executor) SaveGitHubActions() (string, error) {
	if e.plan.GitHubActions == "" {
		return "", nil
	}
	localPath := ".github/workflows/deploy.yml"
	return localPath, nil
}
